id: PBBC55253
initial_creation_type: ocr
source_metadata:
  volumes:
    3eb96b114285433ea4f86967bc04192b:
      base_file: v012.txt
      image_group_id: I1PD95857
      title: རྡོ་རྗེ་རྣལ་འབྱོར་མ་ལ་བསྟོད་པ།
      total_pages: 1544
      volume_number: 12
